# scripts to run before `bun run`-ing a file or script
# register plugins by adding them to this list
preload = ["./tsconfig.json"]



# Reduce memory usage at the cost of performance
smol = false


logLevel = "debug" # "debug" | "warn" | "error"

telemetry = true


[install]
production = false

[run]
# equivalent to `bun --bun` for all `bun run` commands
bun = true

# silent = true
