name: CI

on: [push]

jobs:
  build:
    name: check-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install

      - name: Typecheck
        run: bun typecheck

      - name: build
        run: bun run build